export const PIPELINE_STAGES = [
  { key: "kontakt", label: "Kontakt", color: "#656565" },
  { key: "offert", label: "Offert", color: "#F2BB01" },
  { key: "avslutad_affar", label: "Avslutad (affär)", color: "#333333" },
  { key: "avslutad_ingen_affar", label: "Avslutad (ingen affär)", color: "#8B3D3D" },
] as const;

export type PipelineStage = (typeof PIPELINE_STAGES)[number]["key"];

export const FACTORY_TYPES = [
  { key: "modulfabrik", label: "Modulfabrik" },
  { key: "vagg_tak_fabrik", label: "Vägg & takfabrik" },
] as const;

export type FactoryType = (typeof FACTORY_TYPES)[number]["key"];

export const BUILDING_TYPES = [
  { key: "flerbostadshus", label: "Flerbostadshus" },
  { key: "smahus", label: "Småhus" },
] as const;

export type BuildingType = (typeof BUILDING_TYPES)[number]["key"];

export const CURRENCIES = ["SEK", "EUR", "NOK", "DKK"] as const;

export type Currency = (typeof CURRENCIES)[number];

export const MACHINE_CATEGORIES = [
  { key: "Element Handling", label: "Element Handling" },
  { key: "Module Transport Solutions", label: "Module Transport Solutions" },
] as const;

export type MachineCategory = (typeof MACHINE_CATEGORIES)[number]["key"];

export const USER_ROLES = [
  { key: "admin", label: "Administratör" },
  { key: "salesperson", label: "Säljare" },
] as const;

export type UserRole = (typeof USER_ROLES)[number]["key"];

export const COUNTRIES = [
  "Sverige",
  "Norge",
  "Finland",
  "Danmark",
  "Island",
  "Afghanistan",
  "Albanien",
  "Algeriet",
  "Amerikanska Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antigua och Barbuda",
  "Argentina",
  "Armenien",
  "Aruba",
  "Australien",
  "Azerbajdzjan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belgien",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnien och Hercegovina",
  "Botswana",
  "Brasilien",
  "Brunei",
  "Bulgarien",
  "Burkina Faso",
  "Burundi",
  "Centralafrikanska republiken",
  "Chile",
  "Colombia",
  "Costa Rica",
  "Cypern",
  "Demokratiska republiken Kongo",
  "Dominica",
  "Dominikanska republiken",
  "Djibouti",
  "Ecuador",
  "Egypten",
  "Ekvatorialguinea",
  "El Salvador",
  "Elfenbenskusten",
  "Eritrea",
  "Estland",
  "Eswatini",
  "Etiopien",
  "Fiji",
  "Filippinerna",
  "Frankrike",
  "Förenade Arabemiraten",
  "Gabon",
  "Gambia",
  "Georgien",
  "Ghana",
  "Grekland",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Indien",
  "Indonesien",
  "Irak",
  "Iran",
  "Irland",
  "Israel",
  "Italien",
  "Jamaica",
  "Japan",
  "Jemen",
  "Jordanien",
  "Kambodja",
  "Kamerun",
  "Kanada",
  "Kap Verde",
  "Kazakstan",
  "Kenya",
  "Kina",
  "Kirgizistan",
  "Kiribati",
  "Komorerna",
  "Kongo-Brazzaville",
  "Kosovo",
  "Kroatien",
  "Kuba",
  "Kuwait",
  "Laos",
  "Lesotho",
  "Lettland",
  "Libanon",
  "Liberia",
  "Libyen",
  "Liechtenstein",
  "Litauen",
  "Luxemburg",
  "Madagaskar",
  "Malawi",
  "Malaysia",
  "Maldiverna",
  "Mali",
  "Malta",
  "Marocko",
  "Marshallöarna",
  "Mauretanien",
  "Mauritius",
  "Mexiko",
  "Mikronesien",
  "Moldavien",
  "Monaco",
  "Mongoliet",
  "Montenegro",
  "Moçambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nederländerna",
  "Nepal",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Nordkorea",
  "Nordmakedonien",
  "Nya Zeeland",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua Nya Guinea",
  "Paraguay",
  "Peru",
  "Polen",
  "Portugal",
  "Qatar",
  "Rumänien",
  "Rwanda",
  "Ryssland",
  "Saint Kitts och Nevis",
  "Saint Lucia",
  "Saint Vincent och Grenadinerna",
  "Salomonöarna",
  "Samoa",
  "San Marino",
  "São Tomé och Príncipe",
  "Saudiarabien",
  "Schweiz",
  "Senegal",
  "Serbien",
  "Seychellerna",
  "Sierra Leone",
  "Singapore",
  "Slovakien",
  "Slovenien",
  "Somalia",
  "Spanien",
  "Sri Lanka",
  "Storbritannien",
  "Sudan",
  "Surinam",
  "Sydafrika",
  "Sydkorea",
  "Sydsudan",
  "Syrien",
  "Tadzjikistan",
  "Tanzania",
  "Tchad",
  "Thailand",
  "Tjeckien",
  "Togo",
  "Tonga",
  "Trinidad och Tobago",
  "Tunisien",
  "Turkiet",
  "Turkmenistan",
  "Tuvalu",
  "Tyskland",
  "Uganda",
  "Ukraina",
  "Ungern",
  "Uruguay",
  "USA",
  "Uzbekistan",
  "Vanuatu",
  "Vatikanstaten",
  "Venezuela",
  "Vietnam",
  "Vitryssland",
  "Zambia",
  "Zimbabwe",
  "Österrike",
  "Östtimor",
] as const;
